baseURL = "https://devplayg.com/"
languageCode = "ko-kr"
title = "Developer Playground"
[params]
  author = "Devplayg"
  description = "music makes me high"

[menu]

    [[menu.main]]
    identifier = "music"
    name = "Music"
    title = "Music"
    url = "/music/"
    weight = 4

    [[menu.main]]
    identifier = "tech"
    name = "Tech"
    pre = ""
    url = "/tech/"
    weight = 2

    [[menu.main]]
    identifier = "life"
    name = "Life"
    pre = ""
    url = "/life/"
    weight = 3

    [[menu.main]]
    identifier = "about"
    name = "About"
    pre = ""
    url = "/about/"
    weight = 1
