baseUrl = "https://devplayg.com/"
languageCode = "ko-kr"

author = "devplayg"
title = "DevPlayG"

theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "https-devplayg-github-io"
googleAnalytics = "UA-112382230-1"
# enableRobotsTXT = true
# enableEmoji = true


summarylength = 10

paginate = 1
pluralizelisttitles = false



[params]
    author = "devplayg"
    #description = "technology, thoughts, opinions, rants"
    authorimage = "img/avatar.png"
    dateformat = "Jan 2, 2006"
    copyright = "devplayg"

    highlightjs = true
    highlightjsstyle = "monokai"

[params.meta]
    description = "devplayg's blog :: technology, thoughts, opinions, and music"
    keywords = "blog,tech,utils,golang,life,music"


[params.social]
    github = "devplayg"
    twitter = "devplayg"

    relatedPosts = true



[menu]
    [[menu.main]]
        identifier = "tech"
        # pre = "<i class='fa fa-heart'></i>"
        post = "<span class='alert'>New!</span>"
        name = "Tech"
        weight = 200
        url = "/tech/"

    [[menu.main]]
        identifier = "music"
        name = "Music"
        weight = 300
        url = "/music/"

    [[menu.main]]
        identifier = "life"
        name = "Life"
        weight = 500
        url = "/life/"

    [[menu.main]]
        name = "About"
        weight = 900
        identifier = "about"
        url = "/about/"


