baseUrl = "https://devplayg.com/"
languageCode = "ko-kr"

author = "devplayg"
title = "DevPlayG"

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "https-htr3n-github-io" # Comment out to disable Disqus.
googleAnalytics = "UA-112382230-1"
# enableRobotsTXT = true
# enableEmoji = true


summarylength = 30

paginate = 7
pluralizelisttitles = false



[params]
    author = "devplayg"
    #description = "technology, thoughts, opinions, rants"
    authorimage = "img/avatar.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "monokai"

[params.social]
    github = "devplayg"

# [permalinks]
#     posts = "/:year/:month/:slug/"
#     vn = "/:year/:month/:slug/"

# baseURL         = "https://devplayg.com/"
# languageCode    = "ko-kr"
# title           = "Developer Playground"
# theme           = "hyde-hyde"
#
# [params]
# author      = "Devplayg"
# description = "code makes me high"
#

[menu]
    [[menu.main]]
        identifier = "tech"
        # pre = "<i class='fa fa-heart'></i>"
        post = "<span class='alert'>New!</span>"
        name = "Tech"
        weight = 200
        url = "/tech/"

    [[menu.main]]
        identifier = "music"
        name = "Music"
        weight = 300
        url = "/music/"

    [[menu.main]]
        identifier = "life"
        name = "Life"
        weight = 500
        url = "/life/"

    [[menu.main]]
        name = "About"
        weight = 900
        identifier = "about"
        url = "/about/"
