baseURL = "https://devplayg.com/"
languageCode = "ko-kr"
title = "Developer Playground"
[params]
  author = "Devplayg"
  description = "music makes me high"

[menu]

    [[menu.main]]
    identifier = "music"
    name = "Music"
    title = "Music"
    url = "/music/"
    weight = 2

    [[menu.main]]
    identifier = "golang"
    name = "Golang"
    pre = "<i class='fa fa-heart'></i>"
    url = "/golang/"
    weight = 3

     [[menu.main]]
    identifier = "sansoo"
    name = "Sansoo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/sansoo/"
    weight = 4

    [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 90